version: '3.8'

services:
  web-church:
    image: web-church:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MERCADO_PAGO_ACCESS_TOKEN=${MERCADO_PAGO_ACCESS_TOKEN}
    deploy:
      replicas: 1