version: '3.8'

services:
  web-church:
    build:
      context: .
      dockerfile: Dockerfile
    image: web-church:latest
    ports:
      - "3000:3000"
    environment:
      - ENV=production
      - MERCADO_PAGO_ACCESS_TOKEN=${MERCADO_PAGO_ACCESS_TOKEN}
      - MERCADO_PAGO_PUBLIC_KEY=${MERCADO_PAGO_PUBLIC_KEY}
    restart: always
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s